name: Internal_ESLint_Rules_Test

on:
  push:
    paths:
      - "scripts/tools/eslint-plugin-prettier-internal-rules/**"
      - ".github/workflows/eslint-rules.yml"
  pull_request:
    paths:
      - "scripts/tools/eslint-plugin-prettier-internal-rules/**"
      - ".github/workflows/eslint-rules.yml"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Setup Node.js
        uses: actions/setup-node@v2.5.1
        with:
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Test
        run: cd scripts/tools/eslint-plugin-prettier-internal-rules && yarn test-coverage
